name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        tags: |
          type=sha,prefix=,format=short
      env:
          DOCKER_METADATA_SHORT_SHA_LENGTH: 8
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build image
      run: |
        docker build . -t ${{ vars.REGISTRY_URL }}/mm-haproxy:main -t ${{ vars.REGISTRY_URL }}/mm-haproxy:${{ steps.meta.outputs.tags }}

    - name: Push image
      run: |
        docker push ${{ vars.REGISTRY_URL }}/mm-haproxy:main &&
        docker push ${{ vars.REGISTRY_URL }}/mm-haproxy:${{ steps.meta.outputs.tags }}
